name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Download dependencies
        run: go mod download

      - name: Build
        run: go build -v ./...

      # TODO: Re-enable tests after fixing keyring issues in CI
      # - name: Test
      #   run: go test -v ./...

      - name: Build CLI binary
        run: go build -o supabase-cli .

      - name: Test CLI binary
        run: ./supabase-cli --help

  npm-install-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Test npm install (without postinstall)
        run: npm install --ignore-scripts

      - name: Test postinstall script manually
        run: |
          echo "Testing postinstall script..."
          node scripts/postinstall.js
          
      - name: Verify binary installation
        run: |
          echo "Checking if binary was installed..."
          ls -la bin/
          if [ -f "bin/supabase" ]; then
            echo "Binary found at bin/supabase"
            ./bin/supabase --help | head -5
          else
            echo "Binary not found at bin/supabase"
            exit 1
          fi

  github-packages-test:
    runs-on: ubuntu-latest
    # Only run if there's a release available to test against
    if: github.event_name == 'push'
    steps:
      - name: Create test project
        run: |
          mkdir -p /tmp/test-project
          cd /tmp/test-project
          npm init -y

      - name: Configure GitHub Packages registry
        run: |
          cd /tmp/test-project
          echo "@notreeteam:registry=https://npm.pkg.github.com" > .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> .npmrc

      - name: Test GitHub Packages installation
        run: |
          cd /tmp/test-project
          # Try to install the package - this will only work if a release exists
          if npm install @notreeteam/supabase-cli@latest 2>/dev/null; then
            echo "✅ Package installation successful"
            npx supabase --help | head -5
          else
            echo "⚠️  Package not available yet (no release published)"
            exit 0  # Don't fail the build, just skip
          fi
