name: Publish to NPM

on:
  release:
    types: [published]

permissions:
  contents: read
  packages: write

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Update package.json version
        run: |
          # Extract version from release tag (remove 'v' prefix)
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "Publishing version: $VERSION"
          
          # Update package.json with the release version
          jq --arg version "$VERSION" '.version = $version' package.json > package.json.tmp
          mv package.json.tmp package.json
          
          # Verify the version was updated
          echo "Updated package.json version:"
          jq .version package.json

      - name: Install dependencies
        run: npm install

      - name: Publish to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub Package
        run: |
          # Also publish to GitHub Packages for backup
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > .npmrc
          echo "@notreeteam:registry=https://npm.pkg.github.com" >> .npmrc
          
          # Update package.json for GitHub packages
          jq '.name = "@notreeteam/supabase-cli"' package.json > package.json.tmp
          mv package.json.tmp package.json
          
          npm publish --registry https://npm.pkg.github.com/
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
