name: Setup CLI
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-cli
        with:
          repo: supabase/cli
          version: latest
      - run: supabase --version
